
import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { ModalProvider } from '@/components/providers/modal-provider'
import { SocketProvider } from '@/components/providers/socket-provider'
import { QueryProvider } from '@/components/providers/query-provider'
import Head from 'next/head'
import ClientOnly from '@/components/client-only'
import ClientSideEffects from '@/components/client-side-effects'
import { useTheme } from 'next-themes'


const font = Open_Sans({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Million Chat',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: { apple: '/icon.png' },
  viewport: "width=device-width, initial-scale=1.0",
  themeColor: '#fff'
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { theme } = useTheme();

  // Deduce the theme color based on the current theme
  const themeColor = theme === 'dark' ? '#313338' : '#fff';
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <Head>
          <meta name="apple-mobile-web-app-capable" content="yes" />
          <meta name="apple-mobile-web-app-status-bar-style" content="default" />
          <meta name="theme-color" content={themeColor} />
        </Head>
        <body className={cn(
          font.className, "bg-white dark:bg-[#313338]"
        )}>
          <ClientOnly>
            <ThemeProvider
              attribute='class'
              defaultTheme='dark'
              enableSystem={false}
              storageKey='million-theme'>
              <SocketProvider>
                <ModalProvider />
                <QueryProvider>
                  {children}
                </QueryProvider>
              </SocketProvider>
            </ThemeProvider>
          </ClientOnly>
        </body>
      </html>
    </ClerkProvider>
  );
}
