
import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { ModalProvider } from '@/components/providers/modal-provider'
import { SocketProvider } from '@/components/providers/socket-provider'
import { QueryProvider } from '@/components/providers/query-provider'
import Head from 'next/head'


const font = Open_Sans({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Million Chat',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: {apple:'/icon.png'},
  themeColor: '#fff'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
        <Head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
        </Head>
      <body className={cn (
        font.className, "bg-white dark:bg-[#313338]"
        )}>
        <ThemeProvider
         attribute='class'
         defaultTheme='dark'
         enableSystem={false}
         storageKey='million-theme'>
          <SocketProvider>
          <ModalProvider/>
          <QueryProvider>
                {children}
          </QueryProvider>
            </SocketProvider>
          </ThemeProvider>
        </body>
    </html>
    </ClerkProvider>
  )
}
