"use client";
import type { Metadata } from 'next'
import { useTheme } from 'next-themes';
import { useEffect } from 'react';

export const metadata: Metadata = {
    title: 'Million Chat',
    description: 'Generated by create next app',
    manifest: '/manifest.json',
    icons: { apple: '/icon.png' },
    viewport: "width=device-width, initial-scale=1.0",
    themeColor: '#313338'
};

export default function ClientSideEffects() {
    const { theme } = useTheme();

    useEffect(() => {
        if (theme === 'dark') {
            metadata.themeColor = '#313338'; // Dark mode color
        } else {
            metadata.themeColor = '#fff'; // Light mode color
        }
    }, [theme]);

    return null;
}
